name: lab
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_gen: ^4.3.0
  flutter_svg: ^1.1.0
  json_annotation: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_gen_runner: ^4.3.0
  json_serializable: ^6.2.0
  build_runner: ^2.1.11

flutter_gen:
  output: lib/resources/

  integrations:
    flutter_svg: true

  colors:
    inputs:
      - assets/color/colors.xml

flutter:
  uses-material-design: true

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/nunito/nunito-v16-latin-200.ttf
          weight: 200
        - asset: assets/fonts/nunito/nunito-v16-latin-300.ttf
          weight: 300
        - asset: assets/fonts/nunito/nunito-v16-latin-regular.ttf
          weight: 400
        - asset: assets/fonts/nunito/nunito-v16-latin-600.ttf
          weight: 600
        - asset: assets/fonts/nunito/nunito-v16-latin-700.ttf
          weight: 700
        - asset: assets/fonts/nunito/nunito-v16-latin-800.ttf
          weight: 800
        - asset: assets/fonts/nunito/nunito-v16-latin-900.ttf
          weight: 900
        - asset: assets/fonts/nunito/nunito-v16-latin-200italic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/nunito/nunito-v16-latin-300italic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/nunito/nunito-v16-latin-italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/nunito/nunito-v16-latin-600italic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/nunito/nunito-v16-latin-700italic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/nunito/nunito-v16-latin-800italic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/nunito/nunito-v16-latin-900italic.ttf
          weight: 900
          style: italic

  assets:
    - assets/
    - assets/audio/
    - assets/icons/
    - assets/images/
